Add support for dirty rects
DisplayLink/evdi pull request #291
Opened 2021-06-25 23:45 UTC by pioto1225

Hi,
I would like to add support for dirty rects using atomic mode setting. Corresponding Gnome/Wayland [change](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1879) is under review. This was tested on Fedora 34, and it works pretty neat. I am looking forward to your feedback.
Thanks.
Piotr

PS. Just for reference: Ubuntu/Debian prototype using legacy KMS [see here](https://github.com/pioto1225/evdi/tree/dirty_rects)

2021-06-28 08:18 UTC, lspintzyk reviewed
1. On which distro/desktop environment/xorg/wayland it is tested? 
2. This needs to build as well for older kernels then 5.0
Please use ./ci/build_against_kernel to test it.

2021-06-28 21:29 UTC, pioto1225 commented
1. Partial updates were tested on Fedora 34 Gnome/Wayland (including Mutter changes). Mutter changes are for Gnome/Wayland only, other compositors could add support. I tested EVDI changes for regression on stock Fedora 34, Debian Bullseye (Gnome Wayland), Ubuntu 20.04 (Gnome Wayland and X11). All OK. 

2. Fixed now, thanks.

2021-06-29 10:45 UTC, lspintzyk commented on module/evdi_modeset.c
> +				EVDI_DEBUG("Atomic update, dirty rect [%d, %d, %d, %d]\n",
I think that evdi_painter_mark_dirty is already logging in dirty rects, and it is doing that in VERBOSE mode. Ihom this line is to be deleted.
Also default log mode is DEBUG so this log is to verbose.

2021-06-29 10:47 UTC, lspintzyk approved these changes
Thanks for doing this! This is fine to me.
Approving and we will merge it soon :)

2021-06-29 11:34 UTC, elguero requested changes

2021-06-29 11:34 UTC, elguero commented on module/evdi_modeset.c
> +#if KERNEL_VERSION(5, 0, 0) <= LINUX_VERSION_CODE
It looks like EL8 has this support present.  You should add a check for it:

`#if KERNEL_VERSION(5, 0, 0) <= LINUX_VERSION_CODE || defined(EL8)`

2021-06-29 18:38 UTC, pioto1225 commented
Great! I have added two changes that were requested.
Thanks!

2021-07-05 09:37 UTC, merged

2021-07-05 09:37 UTC, displaylink-emajewsk commented
Merged. Thanks again, @pioto1225 ! 😇

2021-07-05 12:05 UTC, pioto1225 commented
thank you!